name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
         pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') || echo "Pylint exited with $?, ignoring errors"
    - name: Check Pylint rating
            run: |
              pylint_rating=$( pylint --list-msgs | awk '$2 == "rating" { print $1 }' )
              if [[ $pylint_rating > "5.0" ]]; then
                echo "Pylint rating is 5.0, marking workflow as success"
              else
                echo "Pylint rating is not 5.0, marking workflow as failure"
                exit 1
              fi